name: Static checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Format vcpkg.json
        run: |
          vcpkg format-manifest --all $(find . -name "vcpkg.json")
